name: Valoguide
description: A valorant companion App for the community.

version: 1.0.0+6

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  configurable_expansion_tile: ^1.0.0
  flutter_launcher_icons: ^0.7.5
  youtube_player_flutter: ^7.0.0+3
  flutter_cache_manager: ^1.4.0
  photo_view: ^0.9.2
  firebase_admob: ^0.9.3+2
  provider: ^4.1.3
  http: ^0.12.1
  shimmer: ^1.1.1
  html: ^0.14.0+3
  rate_my_app: ^0.6.1+6

flutter_icons:
  image_path: "assets/icons/icon.png"
  ios: true
  android: true

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/agents/port/
    - assets/images/agents/abilities/
    - assets/images/agents/abilities/charges/
    - assets/images/agents/classes/
    - assets/images/agents/avatar/
    - assets/images/weapons/
    - assets/images/weapons/weaponsCard/
    - assets/images/background/
    - assets/images/dashboard/
    - assets/images/maps/
    - assets/images/newsCovers/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see

  # For details regarding adding assets from package dependencies, see

  fonts:

    - family: Valorant
      fonts:
        - asset: assets/fonts/Valorant Font.ttf

    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron.otf

    - family: Tisa Sans
      fonts:
        - asset: assets/fonts/TisaSansPro.otf